#!/usr/bin/env perl
use strict;
use warnings;

use lib qw(..);
use Cwd;
use JSON qw( );
use File::Basename;

# Check whether we run in the development mode (current directory),
# or in production mode (all file I/O in /tmp folder).
my($tmp) = ".";
my($templatedir) = ".";
my($imgdir) = ".";
my($fontdir) = "./fonts";
if (dirname(__FILE__) eq "/usr/bin")
{
    $tmp = "/tmp";
    $templatedir = "/usr/share/alacarte";
    $imgdir = $templatedir;
    $fontdir = "$templatedir/fonts";
}

my($filename) = 'alacarte.json';
if (scalar(@ARGV) > 1)
{
	print "Usage: alacarte <json_filename>\n";
	exit;
}
elsif (scalar(@ARGV) == 1)
{
	$filename = $ARGV[0];
}

my($json_text) = do {
    open(my $json_fh, "<:encoding(UTF-8)", $filename)
        or die("Can't open \$filename\": $!\n");
    local $/;
    <$json_fh>
};

my($content_template) = join("", `cat $templatedir/content.tex.in`);
my($card_template) = join("", `cat $templatedir/alacarte.tex.in`);

my($json) = JSON->new;
my($cards) = $json->decode($json_text);

my($index) = 1;
for ( @{$cards->{cards}} ) {
    my($topic) = $_->{topic};
    my($french) = $_->{french};
    my($transcript) = $_->{transcript};
    my($russian) = $_->{russian};

    # Parsing accents to colorize them.
    $french =~ s/'(\w)/\\textcolor{red}{\\'$1}/g;
    $transcript =~ s/'(\w)/\\textcolor{red}{\\'$1}/g;
    $russian =~ s/'(\w)/\\textcolor{red}{\\'$1}/g;

    my($content) = $content_template;
    $content =~ s/#FRENCH#/$french/;
    $content =~ s/#TRANSCRIPT#/$transcript/;
    $content =~ s/#RUSSIAN#/$russian/;
    $content =~ s/#FONTDIR#/$fontdir/g;

    my($content_filename) = sprintf("$tmp/content_%003d", $index);
    open my $fh1, ">", "$content_filename.tex" or die("Could not open file $content_filename.tex: $!");
    print $fh1 $content;
    close $fh1;

    system("cd $tmp && xelatex $content_filename.tex");
    system("rm $content_filename.tex");
    system("rm $content_filename.aux");
    system("rm $content_filename.log");
    system("rm $content_filename.out");
    system("cd $tmp && pdfcrop $content_filename.pdf");
    system("rm $content_filename.pdf");

    my($card) = $card_template;
    opendir my $dh, "$imgdir/artwork";
    my($imgcount) = grep { -f "$imgdir/artwork/$_" } readdir($dh);
    closedir $dh;
    print "The number of images in $imgdir/artwork is $imgcount\n";
    my($imgnum) = sprintf("%02d", (int rand($imgcount)) + 1);
    $card =~ s/#TOPIC#/$topic/;
    $card =~ s/#CONTENT#/$content_filename-crop.pdf/;
    $card =~ s/#IMGDIR#/$imgdir/g;
    $card =~ s/#IMGNUM#/artwork\/$imgnum/g;
    $card =~ s/#FONTDIR#/$fontdir/g;

    my($card_filename) = sprintf("$tmp/alacarte_%003d", $index);
    open my $fh2, ">", "$card_filename.tex" or die("Could not open file $card_filename.tex: $!");
    print $fh2 $card;
    close $fh2;

    system("cd $tmp && xelatex $card_filename.tex");
    system("cd $tmp && xelatex $card_filename.tex");
    system("rm $card_filename.tex");
    system("rm $card_filename.aux");
    system("rm $card_filename.log"); 
    system("rm $card_filename.out");
    system("rm $content_filename-crop.pdf");

    system("convert -quality 00 $card_filename.pdf $card_filename.png");

    if (dirname(__FILE__) eq "/usr/bin")
    {
        my($pwd) = getcwd;
        system("mv $card_filename.pdf $pwd/");
        system("mv $card_filename.png $pwd/");
    }

    $index++; 
}

